### ISSUE TITLE
Test reproducibility of build with open data

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#276]
It's worth checking we can reproduce basic results when open_data_build is set to true here:

https://github.com/nptscot/npt/blob/86ae338b12f523c27fcc290f48105f2e5dbdcab7/parameters.json#L6-L7

**Comment by Robinlovelace** [comment]
This is the error message I'm getting:

```
> targets::tar_make()
Linking to GEOS 3.11.2, GDAL 3.6.2, PROJ 9.2.0; sf_use_s2() is TRUE
✔ skip target param_file
✔ skip target school_points
✔ skip target zones_contextual
✔ skip target parameters
✔ skip target pmtiles_school
✔ skip target study_area
▶ start target od_school
✖ error target od_school
▶ end pipeline [1.75 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Can't compute indices.
Caused by error:
! `order_by` must be a vector, not a primitive function.
>     schools_dl = sf::read_sf("data-raw/school_desire_lines_open.geojson")
> names(schools_dl)
[1] "DataZone" "SeedCode" "count"    "route_id" "bicycle" 
[6] "geometry"
```

**Comment by Robinlovelace** [comment]
As discussed today with @wangzhao0217

**Comment by Robinlovelace** [comment]
Any luck with this @wangzhao0217 ? I plan to take a look now..

**Comment by wangzhao0217** [comment]
seems working so far:
✔ skip target param_file
✔ skip target school_points
✔ skip target zones_contextual
✔ skip target parameters
✔ skip target pmtiles_school
✔ skip target study_area
✔ skip target od_school
✔ skip target zones
▶ start target rs_school_fastest
Getting the fastest routes for school journeys
POSTing the request to create and start the job
Job id: 6043
No data returned yet. Trying again id 6043 every 10 seconds
Sending data, wait...
Routing not complete
\

**Comment by Robinlovelace** [comment]
Cool, thanks @wangzhao0217 and keep us posted at https://github.com/nptscot/npt/issues/276

**Comment by wangzhao0217** [comment]
Hi Robin, I have encountered the error below:
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: 'odjitter' not found

I tried to install it by:
remotes::install_github("itsleeds/od")
remotes::install_github("dabreegster/odjitter", subdir = "r")

> packageVersion("odjitter")
[1] '0.0.0.9000'

but the error still persists. any suggestions?

Regards,
Zhao

**Comment by Robinlovelace** [comment]
> but the error still persists. any suggestions?

Thanks for testing! Try double checking you have correctly installed `odjitter` on your computer. See here: https://github.com/dabreegster/odjitter#installation

You can check you have installed it correctly by typing the following in PowerShell:

```powershell
odjitter
```

You should see something like this:

**Comment by Robinlovelace** [comment]
```
~> odjitter                                                                                                                                     10/17/2023 10:22:33 am
odjitter 0.1.0
Dustin Carlino <dabreegster@gmail.com
Disaggregate origin/destination data from zones to points

USAGE:
    odjitter <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    disaggregate    Fully disaggregate input desire lines into output representing one trip
                        each, with a `mode` column
    help            Print this message or the help of the given subcommand(s)
    jitter          Import raw data and build an activity model for a region
~>                                                                                                                                              10/17/2023 10:22:35 am

```

**Comment by wangzhao0217** [comment]
*I have installed cargo:*
[image: image.png]
*still have the error below:*
---------------------
 PS C:\Users\wangz> cargo install --git
https://github.com/dabreegster/odjitter
    Updating git repository `https://github.com/dabreegster/odjitter`
  Installing odjitter v0.1.0 (
https://github.com/dabreegster/odjitter#da8cfd4f)
    Updating crates.io index
   Compiling odjitter v0.1.0
(C:\Users\wangz\.cargo\git\checkouts\odjitter-2ee039e64a6d7c8d\da8cfd4)
error[E0277]: the trait bound `geozero::geojson::GeoJson<'_>:
flatgeobuf::geozero::GeozeroDatasource` is not satisfied
   --> src\main.rs:126:29
    |
126 |
fgb.add_feature(geozero::geojson::GeoJson(&serde_json::to_string(&feature)?))?;
    |                 -----------
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait
`flatgeobuf::geozero::GeozeroDatasource` is not implemented for
`geozero::geojson::GeoJson<'_>`
    |                 |
    |                 required by a bound introduced by this call
    |
    = help: the following other types implement trait
`flatgeobuf::geozero::GeozeroDatasource`:
              FgbReader<T, FeaturesSelected>
              FgbReader<T, FeaturesSelectedSeek>
note: required by a bound in `FgbWriter::<'a>::add_feature`
   -->
C:\Users\wangz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flatgeobuf-3.27.0\src\file_writer.rs:254
:53
    |
254 |     pub fn add_feature(&mut self, mut feature: impl
GeozeroDatasource) -> Result<()> {
    |                                                     ^^^^^^^^^^^^^^^^^
required by this bound in `FgbWriter::<'a>::add_feature`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `odjitter` (bin "odjitter") due to previous error
error: failed to compile `odjitter v0.1.0 (
https://github.com/dabreegster/odjitter#da8cfd4f)`, intermediate artifacts
can be found at `C:\Users\wangz\.cargo\bin`.
To reuse those artifacts with a future compilation, set the environment
variable `CARGO_TARGET_DIR` to that path.
---------------------
*I have set the environment variable as well: *
[image: image.png]

**Comment by Robinlovelace** [comment]
Looks like you're having issues compiling the Rust crate after running the following command which fails:

```bash
cargo install --git https://github.com/dabreegster/odjitter
```

Surprised because Rust's toolchain is rock solid. Any ideas @dabreegster (author if the odjitter crate)?

Only thought: what version of Rust/Cargo have you installed Zhao?

**Comment by wangzhao0217** [comment]
here is the version info: [image: image.png]

**Comment by Robinlovelace** [comment]
Latest version that does compile for me:

```
cargo install --git https://github.com/dabreegster/odjitter --rev 32fb58bf7f0d68afd3b76b88cf6b1272c5c66828
```

Can you give that a go and let us know how it goes @wangzhao0217 ?

**Comment by wangzhao0217** [comment]
this works: cargo install --git https://github.com/dabreegster/odjitter
--rev 32fb58bf7f0d68afd3b76b88cf6b1272c5c66828
will continue to test
[image: image.png]

**Comment by Robinlovelace** [comment]
Good progress @wangzhao0217, it's 90% done. The error is happening in the final target:

https://github.com/nptscot/npt/blob/8cfee4c791e243f7181a3a6f699b8368315fe0dd/_targets.R#L1168-L1196

I think I know a quick fix, be ready to run 

```bash
git pull # in PowerShell/similar
```

And then in R:

```r
targets::tar_visnetwork(TRUE) # check the status of the build, should mostly be done
targets::tar_make() # re-run failing targets
```

![image](https://github.com/nptscot/npt/assets/1825120/c92222c1-8336-48ba-a2ab-53829876b174)

**Comment by Robinlovelace** [comment]
@wangzhao0217 update on this: I've pushed a change that should mean that it works after you pull down the latest version of the code on this branch.

Just tested and I get:

```
✔ skip target upload_data
▶ start target metadata
Rows: 45 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl  (5): n_segment_cells, min_flow, max_to_route, time_total_mins, time_r_c...
date (1): routing_date
/
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
● built target metadata [0.573 seconds]
▶ end pipeline [1.552 seconds]
```

**Comment by wangzhao0217** [comment]
something different this time:
✔ skip target upload_data
▶ start target metadata
✖ error target metadata
▶ end pipeline [1.22 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: target metadata attempted to run targets::tar_meta() to
during a pipeline, which is unsupported except when format %in% c("file",
"file_fast") and repository == "local", or if you are reading from a data
store that does not belong to the current pipeline. This is because
functions like tar_meta() attempt to access or modify the local data store,
which may not exist or be properly synced in certain situations. Also,
please be aware that some functions like tar_make() and tar_destroy()
should never run inside a target. Please find a different workaround for
your use case.
[image: image.png]

**Comment by Robinlovelace** [comment]
Is that after git pull ? I think the latest on the #299 branch should not great that error because the 'tar metadata' code is commented out.

**Comment by wangzhao0217** [comment]
Yes, it is. I actually re-cloned the repo.

[image: image.png]
[image: image.png]

**Comment by wangzhao0217** [comment]
Hi Robin, I recloned the repo again, but still getting the same errors, is
the error related to " This is because functions like tar_meta() attempt to
access or modify the local data store, which may not exist or be properly
synced in certain situations. "
▶ start target pmtiles_zones
● built target pmtiles_zones [0.35 seconds]
dasymetric_verylow.geojson: No such file or directory
0 features, 4 bytes of geometry and attributes, 0 bytes of string pool, 0
bytes of vertices, 0 bytes of nodes
Did not read any valid geometries
dasymetric_low.geojson: No such file or directory
0 features, 4 bytes of geometry and attributes, 0 bytes of string pool, 0
bytes of vertices, 0 bytes of nodes
Did not read any valid geometries
dasymetric_med.geojson: No such file or directory
0 features, 4 bytes of geometry and attributes, 0 bytes of string pool, 0
bytes of vertices, 0 bytes of nodes
Did not read any valid geometries
dasymetric_high.geojson: No such file or directory
0 features, 4 bytes of geometry and attributes, 0 bytes of string pool, 0
bytes of vertices, 0 bytes of nodes
Did not read any valid geometries
terminate called after throwing an instance of
'pmtiles::pmtiles_magic_number_exception'
  what():  pmtiles magic number exception
▶ start target pmtiles_buildings
● built target pmtiles_buildings [0.2 seconds]
Commit: 8cfee4c791e243f7181a3a6f699b8368315fe0ddrobinlovelace <
***@***.***>16974902497FALSEUpdate to enable open data builds to work
again #276

Not full build or gh command line tool not available
Not uploading files: manually move contents of outputdata (see upload_data
target for details)
▶ start target upload_data
● built target upload_data [0.01 seconds]
▶ start target metadata
✖ error target metadata
▶ end pipeline [8.774 minutes]
/here were 13 warnings (use warnings() to see them)
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: target metadata attempted to run targets::tar_meta() to
during a pipeline, which is unsupported except when format %in% c("file",
"file_fast") and repository == "local", or if you are reading from a data
store that does not belong to the current pipeline. This is because
functions like tar_meta() attempt to access or modify the local data store,
which may not exist or be properly synced in certain situations. Also,
please be aware that some functions like tar_make() and tar_destroy()
should never run inside a target. Please find a different workaround for
your use case.

**Comment by Robinlovelace** [comment]
Hi @wangzhao0217 I realise the cause: I forgot to run `git push` in my haste yesterday. Please run 

```
git pull
```

And try again.

See here for the changes to get it running that I made, just commenting out the offending lines: https://github.com/nptscot/npt/pull/299/commits/dda5b8770de98b111d72b0ad9360b4cc1ceacd9e

**Comment by wangzhao0217** [comment]
yeah!
[image: image.png]

**Comment by Robinlovelace** [comment]
Awesome! Will close the issue now :tada:
